#ifndef CONFIG_H
#define CONFIG_H

#define ENDSTOP_A_PIN GPIO_NUM_11
#define A_AXIS_MAX M_PI / 2.0f - 0.015
#define A_AXIS_MIN -M_PI / 2.0f + 0.015
#define ENDSTOP_A_POSITION A_AXIS_MAX - 0.035

#define ENDSTOP_B_PIN GPIO_NUM_8
#define B_AXIS_MAX M_PI
#define B_AXIS_MIN 0
#define ENDSTOP_B_POSITION M_PI / 9.0f

#define COARSE_HOMING_SPEED 1.5 // rad/s
#define FINE_HOMING_SPEED 0.5   // rad/s
#define POSITION_TOLERANCE 1.0e-2

#define I2C_MASTER_NUM_1 I2C_NUM_0
#define I2C_MASTER_SDA_IO_1 10
#define I2C_MASTER_SCL_IO_1 9

#define I2C_MASTER_NUM_0 I2C_NUM_1
#define I2C_MASTER_SDA_IO_0 18
#define I2C_MASTER_SCL_IO_0 17

#define I2C_FREQ_HZ 400000

#define COMMON_GEAR_RATIO

#define PID_LOOP_FREQUENCY 1000
#define PID_LOG_FREQUENCY_HZ 1
#define PID_FREQ_ALPHA 0.9f
#define PID_LOOP_TIME_ALPHA 0.9f

#define CTRL_SIGNAL_THRESHOLD 0.1f

#define TIMER_GROUP TIMER_GROUP_0
#define TIMER_IDX TIMER_0

#endif // CONFIG_H